In [1]:
import numpy as np
a = np.array([0 ,1, 2, 3])

In [2]:
a

array([0, 1, 2, 3])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
l = range(1000)
%timeit [i**2 for i in l]

352 µs ± 12.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
l = []

In [7]:
a = np.arange(100)
%timeit a**2

788 ns ± 27.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
a = np.array([0 ,1 ,2, 3])
a

array([0, 1, 2, 3])

In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [11]:
b = np.array([[1, 2 ,4], [3, 4, 5]])

In [12]:
b

array([[1, 2, 4],
       [3, 4, 5]])

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
len(b)

2

In [16]:
c = np.array([[[1,2], [2,3], [5, 5]]])

In [17]:
c

array([[[1, 2],
        [2, 3],
        [5, 5]]])

In [18]:
d = np.array([[[1, 2, 3], [4, 5, 6], [5, 3, 2] , [5, 3, 2]]])

In [19]:
d

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 3, 2],
        [5, 3, 2]]])

In [20]:
e = np.array([[[1, 2, 3], [4, 5, 6]], [[5, 3, 2] , [5, 3, 2]]])

In [21]:
e

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 3, 2],
        [5, 3, 2]]])

In [22]:
e.ndim

3

In [23]:
e.shape

(2, 2, 3)

In [24]:
#1d
#2d
#nd

In [25]:
c.shape

(1, 3, 2)

In [26]:
c.ndim

3

In [27]:
e = np.arange(10)

In [28]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b = np.arange(1 ,10, 2)

In [30]:
b

array([1, 3, 5, 7, 9])

In [33]:
a = np.linspace(0, 1, 6) #no of points

In [32]:
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [34]:
a = np.ones((3 ,3))

In [35]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
b = np.zeros((3, 3))

In [37]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [42]:
a = np.diag([1, 2, 3, 4])
#create array using diag function 
#construct a diagonal array

In [43]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
np.diag(a)

array([1, 2, 3, 4])

In [47]:
a = np.random.rand(4) 
#random array

In [46]:
a

array([0.58653351, 0.11248814, 0.42316605, 0.21885128])

In [48]:
b = np.random.rand(4)

In [49]:
b

array([0.94518331, 0.68626864, 0.19395861, 0.40656907])

In [50]:
a = np.random.randn(4)

In [51]:
a

array([-1.2662265 ,  1.31666394,  0.02788337, -0.85548446])

In [52]:
a = np.random.randn(4)

In [53]:
a

array([-1.13692244,  0.25753665,  0.42933832,  1.48298939])

In [54]:
a = np.arange(10)

In [55]:
a.dtype

dtype('int32')

In [56]:
b = np.arange(10, dtype='float64')

In [57]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
a = np.zeros((3, 3))

In [59]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
a.dtype

dtype('float64')

In [61]:
d = np.array([1+2j, 2+4j])

In [62]:
d

array([1.+2.j, 2.+4.j])

In [63]:
d.dtype

dtype('complex128')

In [64]:
b = np.array([True, False, True, False])
b.dtype

dtype('bool')

In [65]:
s = np.array(['Ram', 'Robert', "sdadas"])

In [66]:
s.dtype

dtype('<U6')

In [67]:
a = np.arange(10)

In [68]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a  = np.diag([1,2,3,4])

In [73]:
a[2, 2]

3

In [74]:
a[2, 1] = 5

In [75]:
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 5, 3, 0],
       [0, 0, 0, 4]])

In [76]:
a = np.arange(10)

In [77]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])